"""Turning a run's generated tests into a pull request."""

from __future__ import annotations

import base64
import logging

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

import github_client
from auth import current_user
from security import decrypt_token
from config import get_settings
from db import PipelineRun, Repository, User, get_session

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/analytics/runs", tags=["integrations"])


@router.post("/{run_id}/pull-request")
async def open_pull_request(
    run_id: str,
    user: User = Depends(current_user),
    session: Session = Depends(get_session),
):
    """Open a PR on the run's repository adding the generated test files.

    Uses the account's existing repo scope. Nothing is force-pushed and the
    target repository's own branches are untouched -- a new branch is created.
    """
    run = session.get(PipelineRun, run_id)
    if run is None or run.user_id != user.id:
        raise HTTPException(status_code=404, detail="Run not found.")
    if run.status != "complete":
        raise HTTPException(status_code=400, detail="Only a completed run can open a pull request.")
    if not run.suite_files:
        raise HTTPException(
            status_code=400,
            detail="This run has no generated test files (it was a standalone run, or predates this feature).",
        )
    repo = session.get(Repository, run.repository_id) if run.repository_id else None
    if repo is None:
        raise HTTPException(status_code=404, detail="The run's repository is no longer connected.")

    token = decrypt_token(user.encrypted_access_token)
    if not token:
        raise HTTPException(status_code=401, detail="Reconnect your GitHub account to open a pull request.")

    branch = f"irontest/tests-{run.id[:8]}"
    base = repo.default_branch

    try:
        base_sha = await github_client.default_branch_sha(token, repo.full_name, base)
        await github_client.create_branch(token, repo.full_name, branch, base_sha)

        for f in run.suite_files:
            content_b64 = base64.b64encode(f["content"].encode("utf-8")).decode("ascii")
            await github_client.put_file(
                token,
                repo.full_name,
                f["path"],
                content_b64,
                message=f"test: add IronTest-generated tests ({run.id[:8]})",
                branch=branch,
            )

        executed = run.passed + run.failed + run.errors
        pass_pct = round((run.passed / executed) * 100) if executed else 0
        body = (
            f"Generated by [IronTest](https://github.com) from the requirement:\n\n"
            f"> {run.story_text.strip()}\n\n"
            f"**Result on `{base}`:** {run.passed}/{executed} passed ({pass_pct}%)"
            + (f", confidence {run.confidence_score}/100" if run.confidence_score is not None else "")
            + ".\n\n"
            f"These tests import the repository's real modules. Review them, then merge to "
            f"keep the coverage.\n\n"
            f"_Files added: {', '.join(f['path'] for f in run.suite_files)}_"
        )
        pr = await github_client.create_pull_request(
            token,
            repo.full_name,
            title=f"Add IronTest-generated tests ({run.id[:8]})",
            body=body,
            head=branch,
            base=base,
        )
    except github_client.GitHubError as exc:
        raise HTTPException(status_code=exc.status_code or 502, detail=str(exc)) from exc

    return {"pull_request_url": pr.get("html_url"), "number": pr.get("number"), "branch": branch}
