"""Public run reports: a sanitized view and a Markdown export.

A shared report exposes the run's results only -- story analysis, tests,
outcomes, verdict, fix suggestions. It never carries the owner's identity, the
repository token, or anything from other runs.
"""

from __future__ import annotations

from typing import Any

from db.models import PipelineRun


def public_view(run: PipelineRun) -> dict[str, Any]:
    return {
        "id": run.id,
        "shared": True,
        "mode": run.mode,
        "status": run.status,
        "created_at": run.created_at.isoformat(),
        "story_text": run.story_text,
        "repository": None,  # deliberately omitted from a public report
        "passed": run.passed,
        "failed": run.failed,
        "errors": run.errors,
        "skipped": run.skipped,
        "pass_rate": run.pass_rate,
        "confidence_score": run.confidence_score,
        "duration_seconds": run.duration_seconds,
        "story": run.story_result,
        "tests": run.tests_result,
        "execution": run.execution_result,
        "defects": run.defects_result,
        "fixes": run.fixes_result or [],
        "compare": run.compare_result,
    }


def _bar(rate: float, width: int = 20) -> str:
    filled = round(rate * width)
    return "█" * filled + "░" * (width - filled)


def to_markdown(run: PipelineRun) -> str:
    story = run.story_result or {}
    defects = run.defects_result or {}
    execution = run.execution_result or {}
    results = execution.get("results", [])
    tests_by_id = {t.get("id"): t for t in (run.tests_result or []) if isinstance(t, dict)}
    executed = run.passed + run.failed + run.errors
    pass_pct = round((run.passed / executed) * 100) if executed else 0

    lines: list[str] = []
    lines.append(f"# IronTest report")
    lines.append("")
    lines.append(f"> {run.story_text.strip()}")
    lines.append("")
    lines.append(f"- **Mode:** {'Specification (feature not built)' if run.mode == 'specification' else 'Existing code'}")
    lines.append(f"- **Run at:** {run.created_at.isoformat()}")
    if run.duration_seconds:
        lines.append(f"- **Duration:** {run.duration_seconds:.1f}s")
    lines.append("")

    lines.append("## Result")
    lines.append("")
    lines.append(f"`{_bar(pass_pct / 100)}` **{pass_pct}%** — {run.passed}/{executed} executed passed")
    lines.append("")
    lines.append(f"| Passed | Failed | Errors | Skipped |")
    lines.append(f"| --- | --- | --- | --- |")
    lines.append(f"| {run.passed} | {run.failed} | {run.errors} | {run.skipped} |")
    lines.append("")

    if defects.get("deployment_recommendation"):
        lines.append(
            f"**Verdict:** {defects['deployment_recommendation']} "
            f"(confidence {defects.get('overall_confidence_score', '?')}/100)"
        )
        if defects.get("recommendation_rationale"):
            lines.append("")
            lines.append(f"> {defects['recommendation_rationale']}")
        lines.append("")

    if story.get("acceptance_criteria"):
        lines.append("## Acceptance criteria")
        lines.append("")
        for crit in story["acceptance_criteria"]:
            lines.append(f"- {crit}")
        lines.append("")

    lines.append("## Test cases")
    lines.append("")
    for result in results:
        status = result.get("status", "?")
        icon = {"pass": "✅", "fail": "❌", "error": "🔥", "skipped": "⚪"}.get(status, "•")
        test = tests_by_id.get(result.get("test_id"), {})
        lines.append(f"### {icon} `{result.get('test_id')}` — {test.get('description', 'Generated test')}")
        if test.get("expected_result"):
            lines.append(f"*Expected:* {test['expected_result']}")
        if status in {"fail", "error"} and result.get("error_message"):
            lines.append("")
            lines.append("```")
            lines.append(result["error_message"][:1500])
            lines.append("```")
        lines.append("")

    fixes = run.fixes_result or []
    if fixes:
        lines.append("## Suggested fixes")
        lines.append("")
        lines.append("*Advisory only — nothing was applied.*")
        lines.append("")
        for fix in fixes:
            lines.append(f"### `{fix.get('test_id')}` → `{fix.get('target_file', '?')}` ({fix.get('confidence', 'medium')})")
            if fix.get("explanation"):
                lines.append(fix["explanation"])
            if fix.get("suggested_change"):
                lines.append("")
                lines.append("```diff")
                lines.append(fix["suggested_change"])
                lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by IronTest.*")
    return "\n".join(lines) + "\n"
