import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { api } from "../lib/api";
import { RunResult } from "../components/RunResult";
import { Banner, Button, Label, Spinner, Tag } from "../components/ui";

/** Public, no-auth view of a shared run. Reached at /r/:token. */
export default function PublicReport() {
  const { token } = useParams();
  const [run, setRun] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .publicReport(token)
      .then(setRun)
      .catch((exc) => setError(exc.message))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Spinner />
      </div>
    );
  }

  if (!run) {
    return (
      <div className="mx-auto flex min-h-screen max-w-prose flex-col items-center justify-center gap-4 px-4">
        <Banner>{error || "This report link is invalid or was revoked."}</Banner>
        <Button as="a" href="/">
          Go to IronTest
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <header className="border-b border-line/15 print:border-0">
        <div className="mx-auto flex h-14 w-full max-w-[1000px] items-center justify-between px-4 sm:px-6">
          <span className="font-mono text-sm font-bold uppercase tracking-[0.18em]">Irontest</span>
          <div className="flex items-center gap-2 print:hidden">
            <Button
              as="a"
              href={api.reportMarkdownUrl(token)}
              variant="secondary"
              size="sm"
            >
              Markdown
            </Button>
            <Button size="sm" onClick={() => window.print()}>
              Print / PDF
            </Button>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-[1000px] px-4 py-8 sm:px-6 sm:py-10">
        <div className="mb-6 flex flex-wrap items-center gap-2">
          <Label>Shared report</Label>
          <Tag tone="solid">{run.mode === "specification" ? "Specification" : "Existing code"}</Tag>
          <span className="text-sm text-muted">{new Date(run.created_at).toLocaleString()}</span>
        </div>
        <p className="mb-6 max-w-prose text-base">{run.story_text}</p>

        <RunResult run={run} />

        <p className="mt-10 text-center text-xs text-muted">Generated by IronTest.</p>
      </main>
    </div>
  );
}
