"""Assembles generated cases into a runnable test file.

Test functions are named test_TC_001_... so the runner's JUnit report maps
each result back to the case that produced it. Without that link the UI could
show outcomes but not say which requirement each one belongs to.
"""

from __future__ import annotations

import re

from models import TestCase
from runners.base import GeneratedFile

# Where each ecosystem expects a test file to live for its default runner.
SUITE_PATHS = {
    "python": "tests/test_irontest_generated.py",
    "javascript": "__tests__/irontest.generated.test.js",
    "typescript": "__tests__/irontest.generated.test.ts",
}

PYTHON_HEADER = '''"""Generated by IronTest.

These tests exercise this repository's own modules. They are written to a
temporary checkout and are never committed to your repository.
"""
'''

JS_HEADER = """// Generated by IronTest.
// These tests exercise this repository's own modules. They are written to a
// temporary checkout and are never committed to your repository.
"""


def _safe_identifier(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "_", value or "").strip("_").lower()
    return cleaned[:48] or "case"


def function_name(case: TestCase) -> str:
    """test_TC_001_short_description, stable across runs of the same case."""
    case_id = _safe_identifier(case.id).upper().replace("TC_", "TC_")
    return f"test_{case_id}_{_safe_identifier(case.description)}"[:80]


def _indent_body(lines: list[str]) -> list[str]:
    """Normalize a snippet body to a single level of indentation.

    Models emit bodies both with and without their own `def` line, and with
    inconsistent leading whitespace; this produces one consistent shape.
    """
    body = [line for line in lines if line.strip()]
    if not body:
        return ["    pass"]

    # Drop a leading def line: the caller supplies its own signature.
    if body[0].lstrip().startswith("def "):
        body = body[1:]
        if not body:
            return ["    pass"]

    common = min((len(line) - len(line.lstrip()) for line in body if line.strip()), default=0)
    return [f"    {line[common:]}" if line.strip() else "" for line in body]


def build_python_suite(cases: list[TestCase], imports: list[str]) -> str:
    parts: list[str] = [PYTHON_HEADER, ""]

    seen: set[str] = set()
    for line in imports:
        clean = line.strip()
        if clean and clean not in seen:
            seen.add(clean)
            parts.append(clean)
    parts.append("")

    for case in cases:
        if not case.automated or not case.automation_snippet:
            continue
        parts.append("")
        parts.append(f"def {function_name(case)}():")
        parts.append(f'    """{case.description[:200]}"""')
        parts.extend(_indent_body(case.automation_snippet))

    return "\n".join(parts) + "\n"


def build_js_suite(cases: list[TestCase], imports: list[str]) -> str:
    parts: list[str] = [JS_HEADER, ""]

    seen: set[str] = set()
    for line in imports:
        clean = line.strip()
        if clean and clean not in seen:
            seen.add(clean)
            parts.append(clean)
    parts.append("")

    for case in cases:
        if not case.automated or not case.automation_snippet:
            continue
        body = "\n".join(f"  {line.strip()}" for line in case.automation_snippet if line.strip())
        parts.append("")
        parts.append(f"test({function_name(case)!r}, () => {{")
        parts.append(body)
        parts.append("});")

    return "\n".join(parts) + "\n"


def build_suite(
    cases: list[TestCase],
    imports: list[str],
    *,
    language: str,
) -> list[GeneratedFile]:
    """Test files to write into the checkout, or [] when nothing is runnable."""
    runnable = [case for case in cases if case.automated and case.automation_snippet]
    if not runnable:
        return []

    normalized = (language or "python").lower()
    if normalized in {"javascript", "typescript"}:
        content = build_js_suite(runnable, imports)
    else:
        # Python is the default: the generator is prompted for pytest unless
        # the stack says otherwise, and pytest can collect a plain file.
        normalized = "python"
        content = build_python_suite(runnable, imports)

    return [GeneratedFile(path=SUITE_PATHS[normalized], content=content)]
